[package]
name = "modtree"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = { version = "0.0.1", path = "crates/postgres" }
plan = { version = "0.0.1", path = "crates/plan" }
database = { version = "0.0.1", path = "crates/database" }
tokio = { version = "1.23.0", features = ["full"] }

[[bin]]
path = "crates/core/main.rs"
name = "modtree"
doctest = false
bench = false

[workspace]
members = [
  "crates/postgres",
  "crates/fetcher",
  "crates/database",
  "crates/types",
  "crates/prereqtree",
  "crates/nusmods",
  "crates/plan"
]
exclude = ["crates/experiments"]
