[package]
name = "modtree"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = { version = "0.0.1", path = "crates/postgres" }

[[bin]]
path = "crates/core/main.rs"
name = "modtree"
doctest = false
bench = false

[workspace]
members = [
  "crates/postgres",
  "crates/fetcher",
  "crates/database",
  "crates/types",
  "crates/prereqtree",
  "crates/nusmods"
]
exclude = ["crates/experiments"]
