version: "3.9"

services:
  graph-db:
    image: modtree/graph-db
    stdin_open: true
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=none
    tty: true
    ports:
      - "7474:7474"
      - "7687:7687"
